main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include ('reserva.urls', namespace='reserva')),
    path('', include ('stand.urls', namespace='stand')),
] + static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

reserva/urls.py
from django.urls import path

from . import views

app_name = "reserva"
urlpatterns = [
    path('', views.ReservasListView.as_view(), name='reserva_listar'),
    path('reservas/detail/<int:pk>/', views.ReservaDetailView.as_view(), name='reserva_detalhar'),
    path('reservas/update/<int:pk>/', views.ReservaUpdateView.as_view(), name='reserva_editar'),
    path('reservas/delete/<int:pk>/', views.ReservaDeleteView.as_view(), name='reserva_deletar'),
    path('reservas/create/', views.ReservaCreateView.as_view(), name='reserva_cadastrar'),
]

stand/urls.py
from django.urls import path

from . import views

app_name = "stand"
urlpatterns = [
    path('stand/list', views.StandListView.as_view(), name='stand_listar'),
    path('stand/detail/<int:pk>/', views.StandDetailView.as_view(), name='stand_detalhar'),
    path('stand/update/<int:pk>/', views.StandUpdateView.as_view(), name='stand_editar'),
    path('stand/delete/<int:pk>/', views.StandDeleteView.as_view(), name='stand_deletar'),
    path('stand/create/', views.StandCreateView.as_view(), name='stand_cadastrar'),
]

reserva/models.py
from django.db import models
from stand.models import Stand
    
class Reserva(models.Model):
    cnpj = models.CharField(max_length=100)
    nome_empresa = models.CharField(max_length=100)
    categoria_empresa = models.CharField(max_length=100)
    quitado = models.BooleanField()
    imagem =models.ImageField(default=False)
    stand = models.ForeignKey(Stand, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nome_empresa}"

    
   




 
    
   

stand/models.py
from django.db import models

class Stand(models.Model):
    localizacao = models.CharField(max_length=150)
    valor = models.FloatField()
    
    def __str__(self):
        return f"Localizacao: {self.localizacao}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

reserva/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reserva

class ReservaForm(ModelForm):
    class Meta:
        model = Reserva
        fields = '__all__'
        widgets = {
            'cnpj': forms.TextInput(attrs={'class': 'form-control' }),
            'nome_empresa': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria_empresa': forms.TextInput(attrs={'class': 'form-control'}),
            'stand': forms.Select(attrs={'class': 'form-control'}),
            'imagem': forms.FileInput(attrs={'class': 'form-control'}),
        }

stand/forms.py
from django.forms import ModelForm
from django import forms
from .models import Stand

class StandForm(ModelForm):
    class Meta:
        model = Stand
        fields = '__all__'
        widgets = {
            'localizacao': forms.TextInput(attrs={'class': 'form-control' }),
            'valor': forms.TextInput(attrs={'class': 'form-control'}),
        }

reserva/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.messages import views
from reserva.models import Reserva
from .forms import ReservaForm
from django.core.paginator import Paginator

# Create your views here.

class ReservasListView(generic.ListView):
  model = Reserva
  paginate_by = 1

class ReservaDetailView(generic.DetailView):
  model = Reserva

class ReservaCreateView(views.SuccessMessageMixin, generic.CreateView):
  model = Reserva
  form_class = ReservaForm
  success_url = reverse_lazy("reserva:reserva_listar")
  success_message = "Reserva cadastrada com sucesso!"
  
class ReservaDeleteView(views.SuccessMessageMixin, generic.DeleteView):
  model = Reserva
  success_url = reverse_lazy("reserva:reserva_listar")
  success_message = "Reserva removida com sucesso!"
  
class ReservaUpdateView(views.SuccessMessageMixin, generic.UpdateView):
  model = Reserva
  form_class = ReservaForm
  success_url = reverse_lazy("reserva:reserva_listar")
  success_message = "Reserva atualizada com sucesso!"

stand/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.messages import views
from stand.models import Stand
from .forms import StandForm
from django.core.paginator import Paginator

# Create your views here.

class StandListView(generic.ListView):
  model = Stand
  paginate_by = 1

class StandDetailView(generic.DetailView):
  model = Stand

class StandCreateView(views.SuccessMessageMixin, generic.CreateView):
  model = Stand
  form_class = StandForm
  success_url = reverse_lazy("stand:stand_listar")
  success_message = "Stand cadastrado com sucesso!"
  
class StandDeleteView(views.SuccessMessageMixin, generic.DeleteView):
  model = Stand
  success_url = reverse_lazy("stand:stand_listar")
  success_message = "Stand removido com sucesso!"
  
class StandUpdateView(views.SuccessMessageMixin, generic.UpdateView):
  model = Stand
  form_class = StandForm
  success_url = reverse_lazy("stand:stand_listar")
  success_message = "Stand atualizado com sucesso!"

users/views.py
from django.shortcuts import render

# Create your views here.

reserva/templates/formulario.html
{% extends 'base.html' %}

{% block main %}

<div style="width: 700px; display: grid; justify-content: center; align-items: center; margin-top: 50px; margin-bottom: 50px;">
    <h2 style="margin-top: 50px;"> Cadastrar Reserva </h2>
       
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="cnpj" class="form-label">Cnpj</label>
            {{ form.cnpj }}
        </div>
        
        <div class="mb-3">
            <label for="nome_empresa" class="form-label">Nome da empresa</label>
            {{ form.nome_empresa }}
        </div>

        <div class="mb-3">
            <label for="categoria_empresa" class="form-label">Categoria da empresa</label>
            {{ form.categoria_empresa}}
        </div>
        
        <div class="mb-3">
            <label for="quitado" class="form-label">Quitado</label>
            {{ form.quitado }}
        </div>

        <div class="mb-3">
            <label for="imagem" class="form-label">imagem</label>
            {{ form.imagem }}
        </div>

        <div class="mb-3">
            <label for="stand" class="form-label">Stand</label>
            {{ form.stand }}
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>  
</div>
      
{% endblock %}
   

reserva/templates/reserva/reserva_confirm_delete.html
{% extends 'base.html' %}


{% block style %}]

<style>
    /* Estilos CSS para a página de exclusão de reserva */
    .deleteres{
        padding-top: 30px;
    }
    
    .delete-reservation-container {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f5f5f5;
        border: 1px solid #ddd;
        border-radius: 5px;
    }

    .delete-reservation-title {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }

    .delete-reservation-message {
        font-size: 16px;
        margin-bottom: 20px;
        color: #666;
    }

    .delete-reservation-form {
        text-align: center;
    }

    .confirm-button {
        background: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        margin: 0 auto;
    }
</style>
    
{% endblock %}
    

{% block main %}

<div class="deleteres">
    <div class="delete-reservation-container">
        <h1 class="delete-reservation-title">Excluir Reserva</h1>
    
        <form class="delete-reservation-form" method="post">
            {% csrf_token %}
            <section class="form container-fluid p-5x">
                <p>Você tem certeza que quer deletar a reserva "{{ object }}"?</p>
                {{ form }}
            </section>
            <button class="confirm-button br-button primary block mt-3 mt-sm-0" type="submit">
                <i class="fas fa-check mr-1" aria-hidden="true"></i>
                Confirmar
            </button>
        </form>
    </div>
</div>

    
{% endblock %}
    

reserva/templates/reserva/reserva_detail.html
{% extends 'base.html' %}

{% block main %}
<div style="display: flex; justify-content: center; padding-top: 20px;">
  <div class="card text-center" style="width: 500px; justify-content: center;">
    <div class="card-header">
      <h5>INFORMAÇÕES</h5>
    </div>
    <div class="card-body">
      <p class="card-text">Nome da empresa: {{ object.nome_empresa }}</p>
      <p class="card-text">Categoria: {{ object.categoria_empresa }}</p>
      <p class="card-text">Cnpj: {{ object.cnpj }}</p>
      <p class="card-text">Localização: {{ object.stand.localizacao }}</p>
      <p class="card-text">Valor: {{ object.stand.valor }}</p>
      <p class="card-text">Quitado: {% if object.quitado %} Sim {% else %} Não {% endif %} </p>

    </div>
    <div class="card-footer text-muted">
        <br>
    </div>
</div>

</div>

{% endblock %}

reserva/templates/reserva/reserva_form.html
{% extends 'base.html' %}

{% block main %}
<div style="display: flex;justify-content: center;">
    <div style="width: 700px; display: grid; justify-content: center; align-items: center;  padding-bottom: 100px;">
        <h2 style="margin-top: 50px;"> Cadastrar Reserva </h2>
           
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="cnpj" class="form-label">Cnpj</label>
                {{ form.cnpj }}
            </div>
            
            <div class="mb-3">
                <label for="nome_empresa" class="form-label">Nome da empresa</label>
                {{ form.nome_empresa }}
            </div>
    
            <div class="mb-3">
                <label for="categoria_empresa" class="form-label">Categoria da empresa</label>
                {{ form.categoria_empresa}}
            </div>
            
            <div class="mb-3">
                <label for="quitado" class="form-label">Quitado</label>
                {{ form.quitado }}
            </div>
    
            <div class="mb-3">
                <label for="imagem" class="form-label">imagem</label>
                {{ form.imagem }}
            </div>
    
            <div class="mb-3">
                <label for="stand" class="form-label">Stand</label>
                {{ form.stand }}
            </div>
    
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>  
    </div>

</div>


      
{% endblock %}
   

reserva/templates/reserva/reserva_list.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<style>
  .inicio1 {
    display: grid;
    justify-content: center;
    align-items: center;
  }


  .inicio2 {
    width: 900px;
  }

  .messages{
    color:white;
    display: flex;
    justify-content: center;
  }


  .alert {
    background-color: blueviolet;
    border-color: blueviolet;
    color: white;
  }




  .custom-prev a {
    background-color: #60017c;
    color: white;
  }


  .custom-next a {
    background-color: #60017c;
    color: white;
  }


  .custom-page a {
    background-color: #f2f2f2;
    color: #333;
  }


  .custom-page a:hover {
    background-color: #60017c;
    color: white;
  }

  .sr-only {
    color: rgb(255, 255, 255);
  }
</style>
{% endblock %}


{% block main %}


<!-- ======= Seção Inicial ======= -->
<section id="hero" class="hero">
  <div class="inicio1">
    <div class="inicio2">
      <h2>Bem vindo ao cadastro de reservas!</h2>
      <br>
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <div class="alert alert-primary" role="alert" id="alert">
          {{message}}
        </div>
        {% endfor %}
      </div>
      {% endif %}


    </div>
  </div>
</section>


<!-- ======= Seção de reservasa ======= -->
<section id="portfolio" class="portfolio sections-bg">
  <div class="container" data-aos="fade-up">


    <div class="section-header">
      <h2>Reservas cadastradas</h2>
    </div>


    <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry"
      data-portfolio-sort="original-order" data-aos="fade-up" data-aos-delay="100">


      <div class="row gy-4 portfolio-container">


        {% for object in object_list %}
        <div class="col-xl-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <a href="" data-gallery="portfolio-gallery-app" class="glightbox">
              {% if object.imagem %}
              <img src="{{ object.imagem.url }}" class="img-fluid" alt="">
              {% endif %}
            </a>
            <div class="portfolio-info">
              <h4><a href="" title="More Details">Nome da empresa: {{ object.nome_empresa }}</a></h4>
              <h4><a href="" title="More Details">Categoria da empresa: {{ object.categoria_empresa }} </a></h4>
              <td>
                <a href="{% url 'reserva:reserva_editar' object.pk %}" class="btn btn-primary btn-sm">Editar</a>
                <a href="{% url 'reserva:reserva_deletar' object.pk %}" class="btn btn-danger btn-sm">Remover</a>
                <a href="{% url 'reserva:reserva_detalhar' object.pk %}" class="btn btn-primary btn-sm"
                  style="background-color: black; border-color: black;">Detalhar</a>
              </td>
            </div>
          </div>
        </div><!-- End Item -->


        {% empty %}
        <tr>
          <td colspan="4">
            <p>Não existem reservas cadastradas...</p>
            <br>
            <br>
          </td>
        </tr>




        {% endfor %}
      </div>


    </div>

    <div>
      <nav aria-label="Navegação de página exemplo" style="margin-top: 30px; justify-content: center;">
        <ul class="pagination">
          <li class="page-item custom-prev">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
              <span class="sr-only">Anterior</span>
            </a>
            {% endif %}
          </li>


          {% for page in page_obj.paginator.page_range %}
          <li class="page-item custom-page">
            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
          </li>
          {% endfor %}


          <li class="page-item custom-next">
            {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próximo">
              <span class="sr-only">Próximo</span>
            </a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>




    {% endblock %}

stand/templates/stand/stand_confirm_delete.html
{% extends "base.html" %}


{% block style %}
<style>
    /* Estilos CSS para a página de exclusão de stand */
    .deletestandd{
        padding-top: 30px;
    }
    .delete-stand-container {
        text-align: center;
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f5f5f5;
        border: 1px solid #ddd;
        border-radius: 5px;
    }

    .delete-stand-title {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }

    .delete-stand-message {
        font-size: 16px;
        margin-bottom: 20px;
        color: #666;
    }

    .delete-stand-form {
        text-align: center;
    }

    .confirm-button {
        background: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        margin: 0 auto;
    }
</style>
    
{% endblock %}
    


{% block main %}

<div class="deletestandd">
    <div class="delete-stand-container">
        <h1 class="delete-stand-title">Excluir Stand</h1>
    
        <form class="delete-stand-form" method="post">
            {% csrf_token %}
            <section class="form container-fluid p-5x">
                <p>Você tem certeza que quer deletar o stand "{{ object }}"?</p>
                {{ form }}
            </section>
            <button class="confirm-button br-button primary block mt-3 mt-sm-0" type="submit">
                <i class="fas fa-check mr-1" aria-hidden="true"></i>
                Confirmar
            </button>
        </form>
    </div>
</div>

{% endblock %}

stand/templates/stand/stand_detail.html
{% extends 'base.html' %}

{% block main %}
<div style="display: flex; justify-content: center; padding-top: 20px;">
  <div class="card text-center" style="width: 500px; justify-content: center;">
    <div class="card-header">
      <h5>INFORMAÇÕES</h5>
    </div>
    <div class="card-body">
      <p class="card-text">Localização: {{ object.localizacao }}</p>
      <p class="card-text">Valor: {{ object.valor }}</p>
    </div>
    <div class="card-footer text-muted">
        <br>
    </div>
</div>

</div>

{% endblock %}

stand/templates/stand/stand_form.html
{% extends 'base.html' %}

{% block main %}
<div style="display: flex;justify-content: center;">
    <div style="width: 700px; display: grid; justify-content: center; align-items: center;  padding-bottom: 100px;">
        <h2 style="margin-top: 50px;"> Cadastrar Reserva </h2>
           
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="localizacao" class="form-label">Localização</label>
                {{ form.localizacao }}
            </div>
            
            <div class="mb-3">
                <label for="valor" class="form-label">Valor</label>
                {{ form.valor }}
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>  
    </div>

</div>


      
{% endblock %}
   

stand/templates/stand/stand_list.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<style>
  .inicio1 {
    display: grid;
    justify-content: center;
    align-items: center;
  }


  .inicio2 {
    width: 900px;
  }

  .messages{
    color:white;
    display: flex;
    justify-content: center;
  }


  .alert {
    background-color: blueviolet;
    border-color: blueviolet;
    color: white;
  }




  .custom-prev a {
    background-color: #60017c;
    color: white;
  }


  .custom-next a {
    background-color: #60017c;
    color: white;
  }


  .custom-page a {
    background-color: #f2f2f2;
    color: #333;
  }


  .custom-page a:hover {
    background-color: #60017c;
    color: white;
  }

  .sr-only {
    color: rgb(255, 255, 255);
  }
</style>
{% endblock %}


{% block main %}


<!-- ======= Seção Inicial ======= -->
<section id="hero" class="hero">
  <div class="inicio1">
    <div class="inicio2">
      <h2>Bem vindo ao cadastro de Stands!</h2>
      <br>
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <div class="alert alert-primary" role="alert" id="alert">
          {{message}}
        </div>
        {% endfor %}
      </div>
      {% endif %}


    </div>
  </div>
</section>


<!-- ======= Seção de reservasa ======= -->
<section id="portfolio" class="portfolio sections-bg">
  <div class="container" data-aos="fade-up">


    <div class="section-header">
      <h2>Stands cadastrados</h2>
    </div>


    <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry"
      data-portfolio-sort="original-order" data-aos="fade-up" data-aos-delay="100">


      <div class="row gy-4 portfolio-container">


        {% for object in object_list %}
        <div class="col-xl-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <div class="portfolio-info">
              <h4><a href="" title="More Details">Localização: {{ object.localizacao }}</a></h4>
              <h4><a href="" title="More Details">Valor: {{ object.valor }} </a></h4>
              <td>
                <a href="{% url 'stand:stand_editar' object.pk %}" class="btn btn-primary btn-sm">Editar</a>
                <a href="{% url 'stand:stand_deletar' object.pk %}" class="btn btn-danger btn-sm">Remover</a>
                <a href="{% url 'stand:stand_detalhar' object.pk %}" class="btn btn-primary btn-sm"
                  style="background-color: black; border-color: black;">Detalhar</a>
              </td>
            </div>
          </div>
        </div><!-- End Item -->


        {% empty %}
        <tr>
          <td colspan="4">
            <p>Não existem stands cadastrados...</p>
            <br>
            <br>
          </td>
        </tr>




        {% endfor %}
      </div>


    </div>

    <div>
      <nav aria-label="Navegação de página exemplo" style="margin-top: 30px; justify-content: center;">
        <ul class="pagination">
          <li class="page-item custom-prev">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
              <span class="sr-only">Anterior</span>
            </a>
            {% endif %}
          </li>


          {% for page in page_obj.paginator.page_range %}
          <li class="page-item custom-page">
            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
          </li>
          {% endfor %}


          <li class="page-item custom-next">
            {% if page_obj.has_next %}
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próximo">
              <span class="sr-only">Próximo</span>
            </a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>




    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ReservaStand</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'admin/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'admin/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'admin/assets/css/main.css' %}" rel="stylesheet">


  <!-- Vendor CSS Files -->
  <link href="{% static 'admin/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'admin/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'admin/assets/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'admin/css/custom_style.css' %}" rel="stylesheet">

  {% block style %}

  {% endblock %}

  
</head>
        <!-- Nav Bar conteudo  -->


<body>

  <!-- ======= Cabeçalho ======= -->
  <header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="{% url 'reserva:reserva_listar' %}" class="logo d-flex align-items-center">
        <h1>StandFinecap</h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'reserva:reserva_cadastrar' %}">Cadastrar Reserva</a></li>
          <li><a href="{% url 'stand:stand_cadastrar' %}">Cadastrar Stand</a></li>
          <li><a href="{% url 'reserva:reserva_listar' %}">Reservas</a></li>
          <li><a href="{% url 'stand:stand_listar' %}">Stands</a></li>
          <li><a href="{% url 'account_signup' %}">Cadastre-se</a></li>
          <li><a href="{% url 'account_login' %}">Entrar</a></li> 
          <li><a href="{% url 'account_logout' %}">Sair</a></li> 
        </ul>    
      </nav>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    </div>
  </header>


  <main id="main">
    {% block main %}

    {% endblock %}

  </main><!-- End #main -->

  
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">

      <div class="row gy-4">

        <div class="col-lg-5 col-md-12 footer-info">
          <a href="" class="logo d-flex align-items-center">
            <img src="" class="img-fluid" alt="" data-aos="zoom-out" data-aos-delay="100" style="height: 100%" >
          </a>
          <p>IFRN - Campus Pau dos Ferros.</p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Info</h4>
          <ul>
            <li><a href="#">Git-Hub</a></li>
            <li><a href="#">outra coisa</a></li>
            <li><a href="#">outra</a></li>
            <li><a href="#">outra</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Links úteis</h4>
          <ul>
            <li><a href="#">Início</a></li>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">Página do IFRN</a></li>
            <li><a href="#">Suap</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contato</h4>
          <p>
            BR-405 S/N,<br>
            Pau dos Ferros - RN,<br>
            59900-000 - Brasil<br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>
        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>FINECAP</span></strong>. All Rights Reserved
      </div>
    </div>

  </footer>

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'admin/assets/vendor/php-email-form/validate.js' %}"></script>
  <script>var staticImagePath = "{% static 'admin/assets/img/PagPodcastsVideos.png' %}";</script>

  <!-- Template Main JS File -->
  <script src="{% static 'admin/assets/js/main.js' %}"></script>
  <div vw class="enabled">
    <div vw-access-button class="active"></div>
    <div vw-plugin-wrapper>
      <div class="vw-plugin-top-wrapper"></div>
    </div>
  </div>
</body>

</html>